### ISSUE TITLE
Please make visiable / usable in Platform IO library manager.

### ISSUE THREAD

**Issue by DavidCBarrett** [tfeldmann/Arduino-Timeout#1]
This is a great little library, sooo much better than DIY timeouts with variables and mills() calcs - thank you.

I found it through google, but when i searched for "Arduino-Timeout" in VS Code -> Platform IO home -> Libraries -> Search Libraries nothing is found.

It woud be great if you could make your lib avaialbe through the search & tidy up platformIo.ini / make it easier for others to find.

Thanks! David.

**Comment by tfeldmann** [comment]
Sorry for the late reply, somehow I missed this ticket! It's available in PlatformIO as https://registry.platformio.org/libraries/tfeldmann/Timeout

Unfortunately renaming is not supported by the pio registry.

**Comment by DavidCBarrett** [comment]
Thank you for the reply 👍
