### ISSUE TITLE
Timing errors

### ISSUE THREAD

**Issue by doktordra** [tfeldmann/Arduino-Timeout#3]
Hello, I made 3 periodic timers (200,300,400) and linked them to R, G and B on a diode, and after some time, timing starts to fall apart. Do you know why?

**Comment by tfeldmann** [comment]
Can you post your code?

**Comment by doktordra** [comment]
You are fast :D

```c
#include <Timeout.h>

const int LED_PIN_R = 17;
bool ledR_on = false;

const int LED_PIN_G = 5;
bool ledG_on = false;

const int LED_PIN_B = 18;
bool ledB_on = false;


Timeout timer;

void setup()
{
  Serial.begin(115200);
  pinMode(LED_PIN_R, OUTPUT);
  pinMode(LED_PIN_G, OUTPUT);
  pinMode(LED_PIN_B, OUTPUT);
}

void loop()
{
  if (timer.periodic(200)) {
    ledR_on = !ledR_on;
    digitalWrite(LED_PIN_R, ledR_on);
    Serial.println(ledR_on);
  }
  if (timer.periodic(300)) {
    ledG_on = !ledG_on;
    digitalWrite(LED_PIN_G, ledG_on);
    Serial.println(ledG_on);
  }
  if (timer.periodic(400)) {
    ledB_on = !ledB_on;
    digitalWrite(LED_PIN_B, ledB_on);
    Serial.println(ledB_on);
  }

}
```

**Comment by doktordra** [comment]
I have to trigger multiple timer instances maybe??
Timeout timerR;
Timeout timerG;
Timeout timerB;

**Comment by tfeldmann** [comment]
I think you have to use three separate Timer instances for this - one for each led. The Timers are super lightweight, so this should be no problem 👍

**Comment by doktordra** [comment]
Hahaha I got it the moment you wrote it, sorry!!!
Thaks anyway, you are really quick!

**Comment by tfeldmann** [comment]
No problem! It's working now?

**Comment by doktordra** [comment]
Yep :) I'll let it work for some time, but I see no reason why it shouldn't work now, it was clearly my fault :)

**Comment by tfeldmann** [comment]
Great to hear, good luck then! :)

**Comment by doktordra** [comment]
Thank you for your really great support :)
